"""Tests for ``_find_unique_constraint_name`` in phase26 migration.

The helper looks up a unique constraint by the columns it covers (rather
than by hard-coded name). This is what makes the migration robust to
historical naming inconsistencies — see the migration's docstring for
the full story.

These tests verify the helper directly against a live SQLite database
with constraints set up to mimic the three real-world scenarios:

1. The constraint exists with the explicit name from phase9
   (``uq_housekeeping_item_cycle_target_flag``)
2. The constraint exists with PostgreSQL's auto-generated name
   (``housekeeping_item_cycle_id_target_cc_id_flag_key``) — what an
   earlier version of phase26 hard-coded
3. No matching constraint exists at all (idempotent re-run case)

We also verify the helper is column-set-based, not column-order-based,
and that it doesn't match constraints with extra or missing columns.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest
import sqlalchemy as sa


def _load_phase26_module():
    """Load the phase26 migration as a module for direct testing.

    Alembic migration files aren't on the import path, so we load by file
    path. Caching the module avoids re-loading on every test.
    """
    repo_root = Path(__file__).resolve().parents[2]
    path = repo_root / "alembic" / "versions" / "20260506_phase26_housekeeping_pc.py"
    spec = importlib.util.spec_from_file_location("phase26_migration", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def phase26():
    return _load_phase26_module()


def _make_table(
    *,
    constraint_name: str | None,
    constraint_columns: list[str] | None,
    extra_constraints: list[tuple[str, list[str]]] | None = None,
) -> sa.engine.Engine:
    """Build an in-memory SQLite engine with a ``housekeeping_item`` table.

    SQLite is fine here because we only use SQLAlchemy's Inspector API,
    which is portable. The schema is omitted (``cleanup``) because SQLite
    doesn't support schemas the same way; the helper is invoked with
    ``schema=None`` for tests.
    """
    engine = sa.create_engine("sqlite:///:memory:")
    metadata = sa.MetaData()
    cols: list[sa.Column] = [
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("cycle_id", sa.Integer, nullable=False),
        sa.Column("target_cc_id", sa.Integer, nullable=True),
        sa.Column("target_pc_id", sa.Integer, nullable=True),
        sa.Column("flag", sa.String(20), nullable=True),
        sa.Column("entity_type", sa.String(8), nullable=True),
    ]
    table_args: list = list(cols)
    if constraint_name and constraint_columns:
        table_args.append(sa.UniqueConstraint(*constraint_columns, name=constraint_name))
    for name, columns in extra_constraints or []:
        table_args.append(sa.UniqueConstraint(*columns, name=name))
    sa.Table("housekeeping_item", metadata, *table_args)
    metadata.create_all(engine)
    return engine


# ── Scenario 1: explicit-named constraint (phase9's actual name) ─────────


def test_finds_constraint_with_phase9_explicit_name(phase26) -> None:
    engine = _make_table(
        constraint_name="uq_housekeeping_item_cycle_target_flag",
        constraint_columns=["cycle_id", "target_cc_id", "flag"],
    )
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["cycle_id", "target_cc_id", "flag"],
        )
    assert name == "uq_housekeeping_item_cycle_target_flag"


# ── Scenario 2: auto-generated name (what phase26 originally hard-coded) ─


def test_finds_constraint_with_pg_autogenerated_name(phase26) -> None:
    engine = _make_table(
        constraint_name="housekeeping_item_cycle_id_target_cc_id_flag_key",
        constraint_columns=["cycle_id", "target_cc_id", "flag"],
    )
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["cycle_id", "target_cc_id", "flag"],
        )
    assert name == "housekeeping_item_cycle_id_target_cc_id_flag_key"


# ── Scenario 3: no matching constraint exists (idempotent re-run case) ───


def test_returns_none_when_no_matching_constraint(phase26) -> None:
    engine = _make_table(constraint_name=None, constraint_columns=None)
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["cycle_id", "target_cc_id", "flag"],
        )
    assert name is None


# ── Column-set matching (order doesn't matter, neither does the name) ────


def test_match_is_order_insensitive(phase26) -> None:
    """A constraint built with ``[a, b, c]`` should be findable with
    a query for ``[c, b, a]`` — same set of columns."""
    engine = _make_table(
        constraint_name="uq_anything",
        constraint_columns=["cycle_id", "target_cc_id", "flag"],
    )
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["flag", "cycle_id", "target_cc_id"],
        )
    assert name == "uq_anything"


def test_does_not_match_constraint_with_extra_columns(phase26) -> None:
    """A constraint covering ``(a, b, c, d)`` must not be returned when
    we ask for ``(a, b, c)`` — those are different constraints, both
    semantically and at the DB level."""
    engine = _make_table(
        constraint_name="uq_wide",
        constraint_columns=["cycle_id", "target_cc_id", "flag", "entity_type"],
    )
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["cycle_id", "target_cc_id", "flag"],
        )
    assert name is None


def test_does_not_match_constraint_with_missing_columns(phase26) -> None:
    """A constraint covering ``(a, b)`` must not be returned when we ask
    for ``(a, b, c)`` — same reason."""
    engine = _make_table(
        constraint_name="uq_narrow",
        constraint_columns=["cycle_id", "target_cc_id"],
    )
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["cycle_id", "target_cc_id", "flag"],
        )
    assert name is None


def test_picks_correct_one_when_multiple_unique_constraints_exist(phase26) -> None:
    """A table can have several unique constraints; the helper must pick
    the one whose column set matches exactly."""
    engine = _make_table(
        constraint_name="uq_target",
        constraint_columns=["cycle_id", "target_cc_id", "flag"],
        extra_constraints=[
            ("uq_other_narrow", ["cycle_id", "target_cc_id"]),
            ("uq_other_wide", ["cycle_id", "target_cc_id", "flag", "entity_type"]),
        ],
    )
    with engine.connect() as conn:
        name = phase26._find_unique_constraint_name(
            conn,
            schema=None,
            table="housekeeping_item",
            columns=["cycle_id", "target_cc_id", "flag"],
        )
    assert name == "uq_target"
