"""Full SAP table alignment: T001, CSKS, CEPC, ZUHL_GRD_GPF.

Adds all remaining SAP standard fields to entity, cost center, profit center,
and employee tables so that direct SAP exports can be loaded without data loss.

Revision ID: phase18_sap_full
Revises: phase17_sap_align
Create Date: 2026-04-28
"""

import sqlalchemy as sa

from alembic import op

revision = "phase18_sap_full"
down_revision = "phase17_sap_align"
branch_labels = None
depends_on = None


def _add_cols(table: str, cols: list[tuple[str, sa.types.TypeEngine]]) -> None:
    """Add columns to a table if they don't already exist."""
    for col_name, col_type in cols:
        op.add_column(
            table,
            sa.Column(col_name, col_type),
            schema="cleanup",
        )


def _drop_cols(table: str, col_names: list[str]) -> None:
    for col_name in col_names:
        op.drop_column(table, col_name, schema="cleanup")


def upgrade() -> None:
    # ---- Entity (T001) — new fields beyond phase17 ----
    _add_cols(
        "entity",
        [
            ("waabw", sa.String(2)),
            ("kokfi", sa.String(1)),
            ("adrnr", sa.String(10)),
            ("stceg", sa.String(20)),
            ("fikrs", sa.String(4)),
            ("xfmco", sa.String(1)),
            ("xfmcb", sa.String(1)),
            ("xfmca", sa.String(1)),
            ("txjcd", sa.String(15)),
            ("fmhrdate", sa.String(8)),
            ("buvar", sa.String(1)),
            ("fdbuk", sa.String(4)),
            ("xfdis", sa.String(1)),
            ("xvalv", sa.String(1)),
            ("xskfn", sa.String(1)),
            ("xmwsn", sa.String(1)),
            ("mregl", sa.String(4)),
            ("xgsbe", sa.String(1)),
            ("xgjrv", sa.String(1)),
            ("xkdft", sa.String(1)),
            ("xprod", sa.String(1)),
            ("xeink", sa.String(1)),
            ("xjvaa", sa.String(1)),
            ("xvvwa", sa.String(1)),
            ("xslta", sa.String(1)),
            ("xfdmm", sa.String(1)),
            ("xfdsd", sa.String(1)),
            ("xextb", sa.String(1)),
            ("ebukr", sa.String(4)),
            ("ktop2", sa.String(4)),
            ("umkrs", sa.String(4)),
            ("bukrs_glob", sa.String(6)),
            ("fstva", sa.String(4)),
            ("opvar", sa.String(4)),
            ("xcovr", sa.String(1)),
            ("txkrs", sa.String(1)),
            ("wfvar", sa.String(4)),
            ("xbbbf", sa.String(1)),
            ("xbbbe", sa.String(1)),
            ("xbbba", sa.String(1)),
            ("xbbko", sa.String(1)),
            ("xstdt", sa.String(1)),
            ("mwskv", sa.String(2)),
            ("mwska", sa.String(2)),
            ("impda", sa.String(1)),
            ("xnegp", sa.String(1)),
            ("xkkbi", sa.String(1)),
            ("wt_newwt", sa.String(1)),
            ("pp_pdate", sa.String(1)),
            ("infmt", sa.String(4)),
            ("fstvare", sa.String(4)),
            ("kopim", sa.String(1)),
            ("dkweg", sa.String(1)),
            ("offsacct", sa.String(1)),
            ("bapovar", sa.String(2)),
            ("xcos", sa.String(1)),
            ("xcession", sa.String(1)),
            ("xsplt", sa.String(1)),
            ("surccm", sa.String(1)),
            ("dtprov", sa.String(2)),
            ("dtamtc", sa.String(2)),
            ("dttaxc", sa.String(2)),
            ("dttdsp", sa.String(2)),
            ("dtaxr", sa.String(4)),
            ("xvatdate", sa.String(1)),
            ("pst_per_var", sa.String(1)),
            ("xbbsc", sa.String(1)),
            ("f_obsolete", sa.String(1)),
        ],
    )

    # ---- LegacyCostCenter (CSKS) — new fields beyond phase17 ----
    _add_cols(
        "legacy_cost_center",
        [
            ("datbi", sa.String(8)),
            ("datab", sa.String(8)),
            ("kalsm", sa.String(6)),
            ("txjcd", sa.String(15)),
            ("logsystem", sa.String(10)),
            ("ersda", sa.String(8)),
            ("usnam", sa.String(12)),
            ("bkzer", sa.String(1)),
            ("bkzob", sa.String(1)),
            ("pkzer", sa.String(1)),
            ("vmeth", sa.String(2)),
            ("mgefl", sa.String(1)),
            ("kvewe", sa.String(1)),
            ("kappl", sa.String(2)),
            ("koszschl", sa.String(6)),
            ("anred", sa.String(15)),
            ("name1", sa.String(35)),
            ("name2", sa.String(35)),
            ("name3", sa.String(35)),
            ("name4", sa.String(35)),
            ("ort01", sa.String(35)),
            ("ort02", sa.String(35)),
            ("stras", sa.String(35)),
            ("pfach", sa.String(10)),
            ("pstlz", sa.String(10)),
            ("pstl2", sa.String(10)),
            ("regio", sa.String(3)),
            ("spras", sa.String(1)),
            ("telbx", sa.String(15)),
            ("telf1", sa.String(16)),
            ("telf2", sa.String(16)),
            ("telfx", sa.String(31)),
            ("teltx", sa.String(30)),
            ("telx1", sa.String(30)),
            ("datlt", sa.String(14)),
            ("drnam", sa.String(4)),
            ("khinr", sa.String(12)),
            ("cckey", sa.String(23)),
            ("kompl", sa.String(1)),
            ("stakz", sa.String(1)),
            ("objnr", sa.String(22)),
            ("funkt", sa.String(3)),
            ("afunk", sa.String(3)),
            ("cpi_templ", sa.String(10)),
            ("cpd_templ", sa.String(10)),
            ("sci_templ", sa.String(10)),
            ("scd_templ", sa.String(10)),
            ("ski_templ", sa.String(10)),
            ("skd_templ", sa.String(10)),
            # CI_CSKS customer fields
            ("zzcuemncfu", sa.String(5)),
            ("zzcueabacc", sa.String(4)),
            ("zzcuegbcd", sa.String(4)),
            ("zzcueubcd", sa.String(4)),
            ("zzcuenkos", sa.String(10)),
            ("zzstrpctyp", sa.String(3)),
            ("zzstrkklas", sa.String(4)),
            ("zzstraagcd", sa.String(2)),
            ("zzstrgfd", sa.String(3)),
            ("zzstrfst", sa.String(2)),
            ("zzstrmacve", sa.String(6)),
            ("zzstrabukr", sa.String(4)),
            ("zzstrugcd", sa.String(4)),
            ("zzstrinadt", sa.String(8)),
            ("zzstrkstyp", sa.String(1)),
            ("zzstrverik", sa.String(20)),
            ("zzstrcurr2", sa.String(3)),
            ("zzstrlccid", sa.String(10)),
            ("zzstrmaloc", sa.String(10)),
            ("zzstrtaxcd", sa.String(4)),
            ("zzstrgrpid", sa.String(4)),
            ("zzstrregcode", sa.String(6)),
            ("zzstrtaxarea", sa.String(10)),
            ("zzstrrepsit", sa.String(10)),
            ("zzstrgsm", sa.String(10)),
            ("zzcemapar", sa.String(10)),
            ("zzledger", sa.String(5)),
            ("zzhdstat", sa.String(1)),
            ("zzhdtype", sa.String(1)),
            ("zzfmd", sa.String(5)),
            ("zzfmdcc", sa.String(3)),
            ("zzfmdnode", sa.String(5)),
            ("zzstate", sa.String(2)),
            ("zztax", sa.String(2)),
            ("zzstrentsa", sa.String(11)),
            ("zzstrentzu", sa.String(11)),
            ("xblnr", sa.String(16)),
            # JV fields
            ("vname", sa.String(6)),
            ("recid", sa.String(2)),
            ("etype", sa.String(3)),
            ("jv_otype", sa.String(4)),
            ("jv_jibcl", sa.String(3)),
            ("jv_jibsa", sa.String(5)),
            ("ferc_ind", sa.String(4)),
        ],
    )

    # ---- LegacyProfitCenter (CEPC) — new fields beyond phase17 ----
    _add_cols(
        "legacy_profit_center",
        [
            ("datbi", sa.String(8)),
            ("datab", sa.String(8)),
            ("ersda", sa.String(8)),
            ("usnam", sa.String(12)),
            ("merkmal", sa.String(30)),
            ("anred", sa.String(15)),
            ("name3", sa.String(35)),
            ("name4", sa.String(35)),
            ("ort01", sa.String(35)),
            ("ort02", sa.String(35)),
            ("stras", sa.String(35)),
            ("pfach", sa.String(10)),
            ("pstlz", sa.String(10)),
            ("pstl2", sa.String(10)),
            ("telbx", sa.String(15)),
            ("telf1", sa.String(16)),
            ("telf2", sa.String(16)),
            ("telfx", sa.String(31)),
            ("teltx", sa.String(30)),
            ("telx1", sa.String(30)),
            ("datlt", sa.String(14)),
            ("drnam", sa.String(4)),
            ("khinr", sa.String(12)),
            ("vname", sa.String(6)),
            ("recid", sa.String(2)),
            ("etype", sa.String(3)),
            ("txjcd", sa.String(15)),
            ("regio", sa.String(3)),
            ("kvewe", sa.String(1)),
            ("kappl", sa.String(2)),
            ("kalsm", sa.String(6)),
            ("logsystem", sa.String(10)),
            ("pca_template", sa.String(10)),
        ],
    )

    # ---- Employee (ZUHL_GRD_GPF) — all SAP fields ----
    _add_cols(
        "employee",
        [
            ("mandt", sa.String(3)),
            ("name", sa.String(40)),
            ("vorname", sa.String(40)),
            ("sprachenschluess", sa.String(1)),
            ("anredecode", sa.String(1)),
            ("userid", sa.String(6)),
            ("eintrittsdatum", sa.String(8)),
            ("oe_leiter", sa.String(1)),
            ("int_tel_nr_1ap", sa.String(20)),
            ("ext_tel_nr_1ap", sa.String(25)),
            ("nl_code_geb_1ap", sa.String(8)),
            ("strasse_geb_1ap", sa.String(30)),
            ("stockwerk_1ap", sa.String(10)),
            ("bueronummer_1ap", sa.String(8)),
            ("kstst", sa.String(10)),
            ("kstst_text", sa.String(20)),
            ("oe_objekt_id", sa.String(8)),
            ("oe_code", sa.String(12)),
            ("oe_text", sa.String(40)),
            ("sap_bukrs", sa.String(4)),
            ("sap_bukrs_text", sa.String(25)),
            ("t_nummer", sa.String(12)),
            ("instrad_1", sa.String(35)),
            ("instrad_2", sa.String(35)),
            ("kstst_einsatz_oe", sa.String(10)),
            ("personalber_text", sa.String(30)),
            ("nl_oe_ma", sa.String(12)),
            ("nl_text", sa.String(40)),
            ("gsfld_oe_ma", sa.String(3)),
            ("gsfld_oe_ma_text", sa.String(30)),
            ("ma_gruppe", sa.String(3)),
            ("ma_gruppe_text", sa.String(20)),
            ("ma_kreis", sa.String(2)),
            ("ma_kreis_text", sa.String(25)),
            ("rang_code", sa.String(4)),
            ("rang_text", sa.String(35)),
            ("akademischer_tit", sa.String(15)),
            ("ubs_funk", sa.String(5)),
            ("ubs_funk_text", sa.String(50)),
            ("gpn_vg_ma", sa.String(8)),
            ("name_vg_ma", sa.String(50)),
            ("ueg_oe_objektid", sa.String(8)),
            ("ueg_oe_bez", sa.String(12)),
            ("ueg_oe_krz", sa.String(40)),
            ("bschgrad", sa.String(3)),
            ("personalbereich", sa.String(4)),
            ("fax_ext_1ap", sa.String(25)),
            ("email_adresse", sa.String(80)),
            ("ma_kz", sa.String(3)),
            ("firma_ext_ma", sa.String(40)),
            ("begdat_orgwechs", sa.String(8)),
            ("austritt_datum", sa.String(8)),
            ("natel_nummer", sa.String(25)),
            ("pager_nummer", sa.String(25)),
            ("plz_geb_1ap", sa.String(10)),
            ("ort_geb_1ap", sa.String(20)),
            ("einsatz_oe_krz", sa.String(12)),
            ("einsatz_oe_text", sa.String(40)),
            ("division", sa.String(14)),
            ("geb_cod_1ap", sa.String(8)),
            ("rang_krz", sa.String(4)),
            ("systemdatum", sa.String(8)),
            ("ap_nummer", sa.String(30)),
            ("einsatz_oe_objid", sa.String(8)),
            ("int_tel_nr_2ap", sa.String(20)),
            ("ext_tel_nr_2ap", sa.String(25)),
            ("bueronummer_2ap", sa.String(8)),
            ("geb_cod_2ap", sa.String(8)),
            ("strasse_geb_2ap", sa.String(30)),
            ("plz_geb_2ap", sa.String(10)),
            ("ort_geb_2ap", sa.String(20)),
            ("geb_cod_geb_2ap", sa.String(8)),
            ("fax_nr_2ap", sa.String(25)),
            ("stockwerk_2ap", sa.String(10)),
            ("gpin_nummer", sa.String(9)),
            ("nat", sa.String(3)),
            ("land_geb_1ap", sa.String(3)),
            ("reg_nr_1ap", sa.String(4)),
            ("postf_1ap", sa.String(30)),
            ("plz_postfadr_1ap", sa.String(10)),
            ("ort_postfadr_1ap", sa.String(20)),
            ("land_geb_2ap", sa.String(3)),
            ("reg_nr_2ap", sa.String(4)),
            ("postf_2ap", sa.String(30)),
            ("plz_postfadr_2ap", sa.String(10)),
            ("ort_postfadr_2ap", sa.String(20)),
            ("letzter_arb_tag", sa.String(8)),
            ("abac_nl_ag_einoe", sa.String(6)),
            ("vertr_ende_exma", sa.String(8)),
            ("untergrp_code", sa.String(4)),
            ("bs_first_name", sa.String(50)),
            ("bs_last_name", sa.String(50)),
            ("name_uc", sa.String(40)),
            ("vorname_uc", sa.String(40)),
            ("name_ph", sa.String(20)),
            ("vorname_ph", sa.String(20)),
            ("ma_oe", sa.String(4)),
            ("updated_id", sa.String(10)),
            ("ma_kstst", sa.String(4)),
            ("business_name", sa.String(50)),
            ("job_categ_code", sa.String(6)),
            ("job_categ_descr", sa.String(30)),
            ("costcenter_code", sa.String(10)),
            ("costcenter_descr", sa.String(50)),
            ("manacs_func_code", sa.String(10)),
            ("manacs_func_desc", sa.String(50)),
            ("manacs_segm_code", sa.String(10)),
            ("manacs_segm_desc", sa.String(50)),
            ("manacs_sect_code", sa.String(10)),
            ("manacs_sect_desc", sa.String(50)),
            ("manacs_bsar_code", sa.String(10)),
            ("manacs_bsar_desc", sa.String(50)),
            ("manacs_bsun_code", sa.String(10)),
            ("manacs_bsun_desc", sa.String(50)),
            ("manacs_bsgp_code", sa.String(10)),
            ("manacs_bsgp_desc", sa.String(50)),
            ("manacs_reg_code", sa.String(10)),
            ("manacs_reg_descr", sa.String(50)),
            ("manacs_loc_code", sa.String(10)),
            ("manacs_loc_descr", sa.String(50)),
            ("regulatory_reg", sa.String(5)),
            ("supervisors_gpin", sa.String(11)),
            ("web_sso", sa.String(20)),
            ("sap_user", sa.String(12)),
            ("hr_company", sa.String(3)),
            ("regulatory_regst", sa.String(3)),
            ("global_cc", sa.String(10)),
        ],
    )


def downgrade() -> None:
    # ---- Employee ----
    _drop_cols(
        "employee",
        [
            "mandt",
            "name",
            "vorname",
            "sprachenschluess",
            "anredecode",
            "userid",
            "eintrittsdatum",
            "oe_leiter",
            "int_tel_nr_1ap",
            "ext_tel_nr_1ap",
            "nl_code_geb_1ap",
            "strasse_geb_1ap",
            "stockwerk_1ap",
            "bueronummer_1ap",
            "kstst",
            "kstst_text",
            "oe_objekt_id",
            "oe_code",
            "oe_text",
            "sap_bukrs",
            "sap_bukrs_text",
            "t_nummer",
            "instrad_1",
            "instrad_2",
            "kstst_einsatz_oe",
            "personalber_text",
            "nl_oe_ma",
            "nl_text",
            "gsfld_oe_ma",
            "gsfld_oe_ma_text",
            "ma_gruppe",
            "ma_gruppe_text",
            "ma_kreis",
            "ma_kreis_text",
            "rang_code",
            "rang_text",
            "akademischer_tit",
            "ubs_funk",
            "ubs_funk_text",
            "gpn_vg_ma",
            "name_vg_ma",
            "ueg_oe_objektid",
            "ueg_oe_bez",
            "ueg_oe_krz",
            "bschgrad",
            "personalbereich",
            "fax_ext_1ap",
            "email_adresse",
            "ma_kz",
            "firma_ext_ma",
            "begdat_orgwechs",
            "austritt_datum",
            "natel_nummer",
            "pager_nummer",
            "plz_geb_1ap",
            "ort_geb_1ap",
            "einsatz_oe_krz",
            "einsatz_oe_text",
            "division",
            "geb_cod_1ap",
            "rang_krz",
            "systemdatum",
            "ap_nummer",
            "einsatz_oe_objid",
            "int_tel_nr_2ap",
            "ext_tel_nr_2ap",
            "bueronummer_2ap",
            "geb_cod_2ap",
            "strasse_geb_2ap",
            "plz_geb_2ap",
            "ort_geb_2ap",
            "geb_cod_geb_2ap",
            "fax_nr_2ap",
            "stockwerk_2ap",
            "gpin_nummer",
            "nat",
            "land_geb_1ap",
            "reg_nr_1ap",
            "postf_1ap",
            "plz_postfadr_1ap",
            "ort_postfadr_1ap",
            "land_geb_2ap",
            "reg_nr_2ap",
            "postf_2ap",
            "plz_postfadr_2ap",
            "ort_postfadr_2ap",
            "letzter_arb_tag",
            "abac_nl_ag_einoe",
            "vertr_ende_exma",
            "untergrp_code",
            "bs_first_name",
            "bs_last_name",
            "name_uc",
            "vorname_uc",
            "name_ph",
            "vorname_ph",
            "ma_oe",
            "updated_id",
            "ma_kstst",
            "business_name",
            "job_categ_code",
            "job_categ_descr",
            "costcenter_code",
            "costcenter_descr",
            "manacs_func_code",
            "manacs_func_desc",
            "manacs_segm_code",
            "manacs_segm_desc",
            "manacs_sect_code",
            "manacs_sect_desc",
            "manacs_bsar_code",
            "manacs_bsar_desc",
            "manacs_bsun_code",
            "manacs_bsun_desc",
            "manacs_bsgp_code",
            "manacs_bsgp_desc",
            "manacs_reg_code",
            "manacs_reg_descr",
            "manacs_loc_code",
            "manacs_loc_descr",
            "regulatory_reg",
            "supervisors_gpin",
            "web_sso",
            "sap_user",
            "hr_company",
            "regulatory_regst",
            "global_cc",
        ],
    )

    # ---- LegacyProfitCenter ----
    _drop_cols(
        "legacy_profit_center",
        [
            "datbi",
            "datab",
            "ersda",
            "usnam",
            "merkmal",
            "anred",
            "name3",
            "name4",
            "ort01",
            "ort02",
            "stras",
            "pfach",
            "pstlz",
            "pstl2",
            "telbx",
            "telf1",
            "telf2",
            "telfx",
            "teltx",
            "telx1",
            "datlt",
            "drnam",
            "khinr",
            "vname",
            "recid",
            "etype",
            "txjcd",
            "regio",
            "kvewe",
            "kappl",
            "kalsm",
            "logsystem",
            "pca_template",
        ],
    )

    # ---- LegacyCostCenter ----
    _drop_cols(
        "legacy_cost_center",
        [
            "datbi",
            "datab",
            "kalsm",
            "txjcd",
            "logsystem",
            "ersda",
            "usnam",
            "bkzer",
            "bkzob",
            "pkzer",
            "vmeth",
            "mgefl",
            "kvewe",
            "kappl",
            "koszschl",
            "anred",
            "name1",
            "name2",
            "name3",
            "name4",
            "ort01",
            "ort02",
            "stras",
            "pfach",
            "pstlz",
            "pstl2",
            "regio",
            "spras",
            "telbx",
            "telf1",
            "telf2",
            "telfx",
            "teltx",
            "telx1",
            "datlt",
            "drnam",
            "khinr",
            "cckey",
            "kompl",
            "stakz",
            "objnr",
            "funkt",
            "afunk",
            "cpi_templ",
            "cpd_templ",
            "sci_templ",
            "scd_templ",
            "ski_templ",
            "skd_templ",
            "zzcuemncfu",
            "zzcueabacc",
            "zzcuegbcd",
            "zzcueubcd",
            "zzcuenkos",
            "zzstrpctyp",
            "zzstrkklas",
            "zzstraagcd",
            "zzstrgfd",
            "zzstrfst",
            "zzstrmacve",
            "zzstrabukr",
            "zzstrugcd",
            "zzstrinadt",
            "zzstrkstyp",
            "zzstrverik",
            "zzstrcurr2",
            "zzstrlccid",
            "zzstrmaloc",
            "zzstrtaxcd",
            "zzstrgrpid",
            "zzstrregcode",
            "zzstrtaxarea",
            "zzstrrepsit",
            "zzstrgsm",
            "zzcemapar",
            "zzledger",
            "zzhdstat",
            "zzhdtype",
            "zzfmd",
            "zzfmdcc",
            "zzfmdnode",
            "zzstate",
            "zztax",
            "zzstrentsa",
            "zzstrentzu",
            "xblnr",
            "vname",
            "recid",
            "etype",
            "jv_otype",
            "jv_jibcl",
            "jv_jibsa",
            "ferc_ind",
        ],
    )

    # ---- Entity ----
    _drop_cols(
        "entity",
        [
            "waabw",
            "kokfi",
            "adrnr",
            "stceg",
            "fikrs",
            "xfmco",
            "xfmcb",
            "xfmca",
            "txjcd",
            "fmhrdate",
            "buvar",
            "fdbuk",
            "xfdis",
            "xvalv",
            "xskfn",
            "xmwsn",
            "mregl",
            "xgsbe",
            "xgjrv",
            "xkdft",
            "xprod",
            "xeink",
            "xjvaa",
            "xvvwa",
            "xslta",
            "xfdmm",
            "xfdsd",
            "xextb",
            "ebukr",
            "ktop2",
            "umkrs",
            "bukrs_glob",
            "fstva",
            "opvar",
            "xcovr",
            "txkrs",
            "wfvar",
            "xbbbf",
            "xbbbe",
            "xbbba",
            "xbbko",
            "xstdt",
            "mwskv",
            "mwska",
            "impda",
            "xnegp",
            "xkkbi",
            "wt_newwt",
            "pp_pdate",
            "infmt",
            "fstvare",
            "kopim",
            "dkweg",
            "offsacct",
            "bapovar",
            "xcos",
            "xcession",
            "xsplt",
            "surccm",
            "dtprov",
            "dtamtc",
            "dttaxc",
            "dttdsp",
            "dtaxr",
            "xvatdate",
            "pst_per_var",
            "xbbsc",
            "f_obsolete",
        ],
    )
